apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/pawel2333/Helm.git
      revision: HEAD
      directories:
      - path: '*'
      - path: 02-mysql
        exclude: true
      - path: 00-nginx
        exclude: true
      - path: appset
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/pawel2333/Helm.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-ns'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true