apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'argocd'
    server: '*'
  - namespace: 'default'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'